# Infrared status for foscam cam in hall
- platform: command_line
  # Command used to get infrared status for a foscam camera:
  # 'curl -k --silent "https://<cam_host>:<cam_port>/cgi-bin/cgi-bin/CGIProxy.fcgi?cmd=getDevState&usr=<username>&pwd=<password>" | grep -oP "(?<=infraLedState>).*?(?=</infraLedState>)"'
  command: !secret cam_foscam_infrared_command
  name: foscam_camara_infrarred
  payload_on: '1'
  payload_off: '0'
 

#   # Alarm status for foscam cam in hall
# - platform: mqtt
#   state_topic: 'home/camera/recibidor/alarm'
#   name: 'recibidor_camara_det_mov'
#   device_class: motion
#   # 0: No alarm
#   # 1: Alarm triggered
#   value_template: >-
#           {%- if value != "0" %}
#               ON
#           {% else %}
#               OFF
#           {%- endif %}