---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Home Control Panel
resources: !include_dir_merge_list lovelace/resources/
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/security.yaml
