resources:
  - url: /local/custom_ui/dark-sky-weather-card.js?v=8
    type: js

title: My Automated Home
# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  
views:
    # View tab title.
  - title: Home
    # Optional unique id for direct access /lovelace/${id}
    id: home
    # Optional background (overwrites the global background).
    #background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    # The cards to show on this view.
    cards:
    #     # The filter card will filter entities for their state
    #   - type: horizontal-stack #entity-filter
    #       card:
    #         - type: picture-entity
    #           image: /local/TST/PhoneState/timo/home.jpg
    #           entity: sensor.timo_status
      - type: horizontal-stack
        cards:
          - type: picture-entity
            state_image:
              "home": /local/TST/PhoneState/timo/home.jpg
              "Away": /local/TST/PhoneState/timo/Away.jpg
            entity: sensor.timo_status
            name: Timo

          - type: picture-entity
            state_image:
              "home": /local/TST/PhoneState/danielle/home.jpg
              "Away": /local/TST/PhoneState/danielle/Away.jpg
            entity: sensor.danielle_status
            name: Danielle

        # The picture entity card will represent an entity with a picture
      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/TST/keuken.jpg
            entity: light.firstfloorlights
            name: Beneden verlichting
            tap_action: toggle

          - type: picture-glance
            image: /local/TST/keuken.jpg
            title: Beneden verlichting
            tap_action: turn-on
            entities:
              - group.keuken
              - light.level_3
              - group.woonkamer

      - type: horizontal-stack
        cards:
          - type: picture-entity
            image: /local/TST/keuken.jpg
            name: keuken
            entity: light.level
            tap_action: toggle
          - type: picture-glance
            image: /local/TST/woonkamer2.jpg
            name: woonkamer
            tap_action: toggle
            entities: 
              - entity: group.woonkamer
                icon: mdi:power
              - entity: switch.switch
                icon: mdi:ceiling-light
              - entity: switch.switch_2
                icon: mdi:ceiling-light
          - type: picture-entity
            image: /local/TST/hal.jpg
            name: Hal
            entity: light.level_3
            tap_action: toggle

      - type: custom:dark-sky-weather-card
        entity_sun: sun.sun
        entity_current_conditions: sensor.dark_sky_icon  
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_temperature: sensor.dark_sky_temperature
        entity_visibility: sensor.dark_sky_visibility
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4
        entity_forecast_icon_1: sensor.dark_sky_icon_1
        entity_forecast_icon_2: sensor.dark_sky_icon_2
        entity_forecast_icon_3: sensor.dark_sky_icon_3
        entity_forecast_icon_4: sensor.dark_sky_icon_4
        entity_forecast_icon_5: sensor.dark_sky_icon_5
        entity_daily_summary: sensor.dark_sky_daily_summary

      # - type: conditional
      #   conditions:
      #     - entity: sensor.trash_today
      #       state_not: "Geen"
      #  card:
      - type: picture-entity
        state_image:
          "GFT": /local/Trash/GroeneBak.jpg
          "PMD": /local/Trash/OranjeBak.jpg
          "Papier": /local/Trash/BlauweBak.jpg
          "Textiel": /local/Trash/TextielZak.png
          "Rest": /local/Trash/GrijzeBak.jpg
          "Geen": /local/Trash/GeenBak.jpg
        entity: sensor.trash_today
        name: Container vandaag

      - type: map
        entities:
        - entity: device_tracker.ce0417142b50872202
        - entity: device_tracker.ce11171b6d4c1f1b04
        - zone.home  
        aspect_ratio: 70%
      - type: media-control
        #entity: media_player.smarttv
        entity: media_player.keuken
        #entity: media_player.woonkamer11
      - type: iframe
        url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=256&h=256" NORESIZE SCROLLING=NO HSPACE=0 VSPACE=0 FRAMEBORDER=0 MARGINHEIGHT=0 MARGINWIDTH=0 WIDTH=256 HEIGHT=256>
      - type: iframe
        url: https://gadgets.buienradar.nl/gadget/zoommap/?lat=52.29917&lng=5.24167&overname=2&zoom=8&naam=1273&size=2&voor=1
      - type: history-graph
        hours_to_show: 8
        refresh_interval: 3600
        entities:
        - entity: sensor.foscammotionsensor
      - type: picture-glance
        title: woonkamer
        entities:
          - switch.switch
          - switch.switch_2
        camera_image: camera.woonkamer1
      - type: picture
        image: /local/cam_captures/LastMotion.jpg
        title: Last Motion
      - type: picture-entity
        image: /local/cam_captures/LastMotion.jpg
        name: Last Motion
        entity: sensor.foscammotionsensor

    # Specify a tab icon if you want the view tab to be an icon.
  - icon: mdi:home-assistant
    # Title of the view. Will be used as the tooltip for tab icon
    title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - group.keuken
          - light.level_3
          - group.woonkamer
          - light.firstfloorlights
          - input_boolean.statuswasmachine

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.