title: Security
icon: mdi:cctv
cards:
  - type: entities
    entities:
      - sensor.alarm_clock_time
      - input_number.alarm_clock_hour
      - input_number.alarm_clock_minute
      - input_boolean.alarm_clock_status

  - type: custom:button-card
    entity: light.fibaro_system_fgd212_dimmer_2_level_2
    name: Kitchen
    icon: mdi:fire
    show_state: true
    styles:
      card:
        - width: 100px
        - height: 100px
      grid:
        - grid-template-areas: '"i" "n" "s"'
        - grid-template-columns: 1fr
        - grid-template-rows: 1fr min-content min-content
      img_cell:
        - align-self: start
        - text-align: start
      name:
        - justify-self: start
        - padding-left: 10px
        - font-weight: bold
        - text-transform: lowercase
      state:
        - justify-self: start
        - padding-left: 10px
    state:
      - value: 'off'
        styles:
          card:
            - filter: opacity(50%)
          icon:
            - filter: grayscale(100%)

  - type: entities
    # Title of the entities card
    title: Example
    # The entities here will be shown in the same order as specified.
    # Each entry is an entity ID or a map with extra options.
    entities:
      - sensor.fibaro_system_fgms001_zw5_motion_sensor_luminance
      - sensor.foscammotionsensor
      - script.foscam_on
      - script.foscam_off

  - type: picture-glance
    image: /local/cam_captures/LastMotion.jpg
    name: Last Motion
    entities:
      - sensor.foscammotionsensor

  - id: a8d7e47eb0ab4ed78b8db6c18bcf28a4  # Automatically created id
    type: history-graph
    hours_to_show: 72
    refresh_interval: 3600
    entities:
      - entity: sensor.foscammotionsensor
      - entity: sensor.FoscamMotionDetectionStatus

  - type: horizontal-stack
    cards:
      - type: iframe
        url: https://api.buienradar.nl/image/1.0/RadarMapNL?w=240&h=250"
        aspect_ratio: 100%
      - type: iframe
        url: https://gadgets.buienradar.nl/gadget/zoommap/?lat=52.29917&lng=5.24167&overname=2&zoom=8&naam=1273&size=2&voor=1
        aspect_ratio: 110%
    
  - type: history-graph
    hours_to_show: 72
    refresh_interval: 3600
    entities:
      - entity: sensor.fibaro_system_fgms001_zw5_motion_sensor_temperature