sensor:
  - platform: template
    sensors:
      time_of_day:
        value_template: >
          {% set current_hour = strptime(states('sensor.time'), "%H:%M").hour %}
          {% if current_hour < 12 %}
            Good Morning
          {% elif 12 <= current_hour < 18 %}
            Good Afternoon
          {% elif 18 <= current_hour < 23 %}
            Good Evening
          {% else %}
            Good Night
          {% endif %}

  ## TIMO PRESENCE SENSORS ## 
  - platform: template
    sensors:
      presence_timo_zone:
        value_template: >
          {% if is_state('device_tracker.ce0417142b50872202', 'not_home') %}
            Away
          {% elif is_state('sensor.timo_status', 'home') %}
            Home
          {% else %}
            {{ states('device_tracker.ce0417142b50872202') }}
          {% endif %}

  - platform: template
    sensors:
      presence_timo_time:
        value_template: >
          {% if is_state('sensor.timo_status', 'home') %}
            -
          {% else %}
            {{ states('sensor.timo2home') + ' MIN' }}
          {% endif %}

  - platform: template
    sensors:
      presence_timo_battery:
        value_template: '{{ states.device_tracker.ce0417142b50872202.attributes.battery|default(0) }}'

  ## DAAN PRESENCE SENSORS ##
  - platform: template
    sensors:
      presence_daan_zone:
        value_template: >
          {% if is_state('device_tracker.ce11171b6d4c1f1b04', 'not_home') %}
            Away
          {% elif is_state('sensor.danielle_status', 'home') %}
            Home
          {% else %}
            {{ states('device_tracker.ce11171b6d4c1f1b04') }}
          {% endif %}

  - platform: template
    sensors:
      presence_daan_time:
        value_template: >
          {% if is_state('sensor.danielle_status', 'home') %}
            -
          {% else %}
            {{ states('sensor.daan2home') + ' MIN' }}
          {% endif %}

  - platform: template
    sensors:
      presence_daan_battery:
        value_template: '{{ states.device_tracker.ce11171b6d4c1f1b04.attributes.battery|default(0) }}'

homeassistant:
  customize:
    input_boolean.statuswasmachine:
      friendly_name: 'statuswasmachine'
      icon: mdi:washing-machine
      templates:
        hs_color: >
          if (state === 'on') {
            return [60,100];
          } else if (state === 'off' ) {
            return [60, 0];
          } else {
            return rgb(35, 76, 99);
          }