homeassistant:
  customize:
    input_text.dummy_tiles_updatecustomui:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 2
        row_height: 54px
        gap: 8px                             
        entities:
          - entity: script.updatecustomui
            label: Update customUI
            icon: mdi:script
            column: 1         
            column_span: 1      
            row: 1                
            color: 'hsl(0, 0%, 80%)'    #grey            
            icon_size: 18px
            text_uppercase: false
          - entity: script.updatetiles
            label: Update tiles
            icon: mdi:script
            column: 2         
            column_span: 1      
            row: 1                
            color: 'hsl(0, 0%, 80%)'    #grey            
            icon_size: 18px
            text_uppercase: false

input_text:
  dummy_tiles_updatecustomui:
    name: dummy_tiles_updatecustomui

script:
    updatecustomui:
      alias: updatecustomui
      sequence:
        - service: shell_command.updatecustomui
    updatetiles:
      alias: updatetiles
      sequence:
        - service: shell_command.updatetiles

sensor:
  - platform: rest
    name: SC Tiles latest version
    resource: https://raw.githubusercontent.com/c727/home-assistant-tiles/master/LATEST_VERSION

# automation:
#   - id: SC Tiles update info
#     alias: SC Tiles update info
#     trigger:
#       - platform: state
#         entity_id: sensor.sc_tiles_latest_version
#     action:
#       - service: telegram_bot.send_message
#         data_template:
#           title: 'CustomUI'
#           target: !secret telegram_Timo_id
#           message: 'A new version for [Tiles custom state card](https://github.com/c727/home-assistant-tiles#changelog) is available.'
#           disable_notification: false

shell_command:
  updatetiles: 'bash /config/updatetiles.sh'
  updatecustomui: 'bash /config/update.sh'