# TURNING FOSCAM C2 ON OFF BASED ON PRESENCE

- alias: 'livingroom_camera_off'
  trigger:
    - platform: state
      entity_id: input_boolean.timohome 
      to: 'on'
      #entity_id: group.family  
      #to: 'not_home'
  condition:
    - condition: time
      after: '06:00:00'
      before: '22:45:00'
  action:
    - service: camera.turn_off
      data:
        entity_id: camera.woonkamer1

- alias: 'livingroom_camera_on'
  trigger:
    - platform: state
      entity_id: input_boolean.timohome 
      to: 'off'
      #entity_id: group.family  
      #to: 'not_home'
  action:
    - service: camera.turn_on
      data:
        entity_id: camera.woonkamer1

- alias: 'livingroom_camera_on_night'
  trigger:
    - platform: time
      at: '23:00:00'
      #entity_id: group.family  
      #to: 'not_home'
  action:
    - service: camera.turn_on
      data:
        entity_id: camera.woonkamer1

- alias: 'livingroom_camera_off_morning'
  trigger:
    - platform: time
      at: '06:00:00'
      #entity_id: group.family  
      #to: 'not_home'
  action:
    - service: camera.turn_off
      data:
        entity_id: camera.woonkamer1
