- alias: 'Timo Away'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.timohome
    state: 'on'
  trigger:
    - platform: state
      entity_id: person.timo
      to: 'not_home' 
      for:
        minutes: 3
    # - platform: state
    #   entity_id: device_tracker.ce0417142b50872202 #GPSLOGGER
    #   to: 'not_home' 
    #   for:
    #     minutes: 3
    # - platform: state
    #   entity_id: device_tracker.30074d51bc9a #Phone Router
    #   to: 'not_home' 
    #   for:
    #     minutes: 3
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.timohome

- alias: 'Timo Home'
  initial_state: 'on'
  condition:
    condition: state
    entity_id: input_boolean.timohome
    state: 'off'
  trigger:
    - platform: state
      entity_id: person.timo
      to: 'home' 
    # - platform: state
    #   entity_id: device_tracker.ce0417142b50872202 #GPSLOGGER
    #   to: 'home' 
    # - platform: state
    #   entity_id: device_tracker.30074d51bc9a #Phone Router
    #   to: 'home'
    # - platform: state
    #   entity_id: device_tracker.galaxy_s8 #BT Timo
    #   to: 'home'   
  action:
    # - service: homeassistant.turn_on
    #   entity_id: input_boolean.timohome
    - delay: 00:01:00
    - service: script.sonos_say
      data:
        sonos_entity: media_player.keuken
        volume: 0.2
        delay: '00:00:04'
        message: 'Welkom thuis Timo!'

- alias: 'HallwayonWhenTimoHome'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: person.timo
      to: 'home'
    # - platform: state
    #   entity_id: device_tracker.ce0417142b50872202 #GPSLOGGER
    #   to: 'home'
    # - platform: state
    #   entity_id: device_tracker.galaxy_s8 #BT Timo
    #   to: 'home'  
    # - platform: state
    #   entity_id: device_tracker.30074d51bc9a #Phone Router
    #   to: 'home' 
  condition:
    - condition: state
      entity_id: input_boolean.timohome
      state: 'off'   
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.timohome
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"  
    - service: light.turn_on
      entity_id: light.domitech_smart_led_retrofit_kit_ze27eu_level
      data:
        brightness: 3
    - service: switch.turn_on
      entity_id: group.woonkamer
    - service: light.turn_on
      entity_id: group.keuken
    - delay: 00:03:00
    - service: light.turn_off
      entity_id: light.domitech_smart_led_retrofit_kit_ze27eu_level


####################################
#### NOTIFY ###

- id: NotifyTimoHome
  alias: NotifyTimoHome
  initial_state: 'on'
  trigger:
  - platform: zone
    event: enter
    zone: zone.Home
    entity_id: person.timo
    # Optional
    #from: 'away'
    # Optional
    #to: 'Home'
  action:
    - service: telegram_bot.send_message
      data_template:
        #title: 'Presence detection'
        target: !secret telegram_Timo_id
        message: 'Timo is Home'
        disable_notification: false 