homeassistant:
  customize:
    input_text.remote_control:
      custom_ui_state_card: state-card-tiles
      config:
        columns: 2
        row_height: 50px
        column_width: 62px
        gap: 15px
        color: '#555B65'
        color_on: '#D5D619'
        color_off: '#BBBEC2'
        entities:
          - entity: script.scene_allelampenuit
            icon: mdi:hotel
            column: 1
            row: 1
          - entity: script.scene_allelampenaan
            icon: mdi:lightbulb
            column: 2
            row: 1
            
input_text:
  remote_control:
    name: remote_control

script:
  scene_allelampenaan:
    sequence:
      - service: homeassistant.turn_on
        entity_id: scene.allelampenaan
  scene_allelampenuit:
    sequence:
      - service: homeassistant.turn_on
        entity_id: scene.allelampenuit
          